package pl.atena.aj.be.music.domain;

import java.io.Serializable;

/**
 * Oficjalna lista gatunków dla standardu ID3 v2.3.0.
 * 
 * http://id3.org/id3v2.3.0
 * 
 */
public enum Genre implements Serializable {

	A_CAPELLA(1, "A capella"),
	ACID(2, "Acid"),
	ACID_JAZZ(3, "Acid Jazz"),
	ACID_PUNK(4, "Acid Punk"),
	ACOUSTIC(5, "Acoustic"),
	ALTERNATIVE(6, "Alternative"),
	ALTERNROCK(7, "AlternRock"),
	AMBIENT(8, "Ambient"),
	AVANTGARDE(9, "Avantgarde"),
	BALLAD(10, "Ballad"),
	BASS(11, "Bass"),
	BEBOB(12, "Bebob"),
	BIG_BAND(13, "Big Band"),
	BLUEGRASS(14, "Bluegrass"),
	BLUES(15, "Blues"),
	BOOTY_BASS(16, "Booty Bass"),
	CABARET(17, "Cabaret"),
	CELTIC(18, "Celtic"),
	CHAMBER_MUSIC(19, "Chamber Music"),
	CHANSON(20, "Chanson"),
	CHORUS(21, "Chorus"),
	CHRISTIAN_RAP(22, "Christian Rap"),
	CLASSIC_ROCK(23, "Classic Rock"),
	CLASSICAL(24, "Classical"),
	CLUB(25, "Club"),
	COMEDY(26, "Comedy"),
	COUNTRY(27, "Country"),
	CULT(28, "Cult"),
	DANCE(29, "Dance"),
	DANCE_HALL(30, "Dance Hall"),
	DARKWAVE(31, "Darkwave"),
	DEATH_METAL(32, "Death Metal"),
	DISCO(33, "Disco"),
	DREAM(34, "Dream"),
	DRUM_SOLO(35, "Drum Solo"),
	DUET(36, "Duet"),
	EASY_LISTENING(37, "Easy Listening"),
	ELECTRONIC(38, "Electronic"),
	ETHNIC(39, "Ethnic"),
	EURO_HOUSE(40, "Euro-House"),
	EURO_TECHNO(41, "Euro-Techno"),
	EURODANCE(42, "Eurodance"),
	FAST_FUSION(43, "Fast Fusion"),
	FOLK(44, "Folk"),
	FOLK_ROCK(45, "Folk-Rock"),
	FOLKLORE(46, "Folklore"),
	FREESTYLE(47, "Freestyle"),
	FUNK(48, "Funk"),
	FUSION(49, "Fusion"),
	GAME(50, "Game"),
	GANGSTA(51, "Gangsta"),
	GOSPEL(52, "Gospel"),
	GOTHIC(53, "Gothic"),
	GOTHIC_ROCK(54, "Gothic Rock"),
	GRUNGE(55, "Grunge"),
	HARD_ROCK(56, "Hard Rock"),
	HIP_HOP(57, "Hip-Hop"),
	HOUSE(58, "House"),
	HUMOUR(59, "Humour"),
	INDUSTRIAL(60, "Industrial"),
	INSTRUMENTAL(61, "Instrumental"),
	INSTRUMENTAL_POP(62, "Instrumental Pop"),
	INSTRUMENTAL_ROCK(63, "Instrumental Rock"),
	JAZZ(64, "Jazz"),
	JAZZ_FUNK(65, "Jazz+Funk"),
	JUNGLE(66, "Jungle"),
	LATIN(67, "Latin"),
	LO_FI(68, "Lo-Fi"),
	MEDITATIVE(69, "Meditative"),
	METAL(70, "Metal"),
	MUSICAL(71, "Musical"),
	NATIONAL_FOLK(72, "National Folk"),
	NATIVE_AMERICAN(73, "Native American"),
	NEW_AGE(74, "New Age"),
	NEW_WAVE(75, "New Wave"),
	NOISE(76, "Noise"),
	OLDIES(77, "Oldies"),
	OPERA(78, "Opera"),
	OTHER(79, "Other"),
	POLKA(80, "Polka"),
	POP(81, "Pop"),
	POP_FOLK(82, "Pop-Folk"),
	POP_FUNK(83, "Pop/Funk"),
	PORN_GROOVE(84, "Porn Groove"),
	POWER_BALLAD(85, "Power Ballad"),
	PRANKS(86, "Pranks"),
	PRIMUS(87, "Primus"),
	PROGRESSIVE_ROCK(88, "Progressive Rock"),
	PSYCHADELIC(89, "Psychadelic"),
	PSYCHEDELIC_ROCK(90, "Psychedelic Rock"),
	PUNK(91, "Punk"),
	PUNK_ROCK(92, "Punk Rock"),
	R_B(93, "R&B"),
	RAP(94, "Rap"),
	RAVE(95, "Rave"),
	REGGAE(96, "Reggae"),
	RETRO(97, "Retro"),
	REVIVAL(98, "Revival"),
	RHYTHMIC_SOUL(99, "Rhythmic Soul"),
	ROCK(100, "Rock"),
	ROCK_ROLL(101, "Rock & Roll"),
	SAMBA(102, "Samba"),
	SATIRE(103, "Satire"),
	SHOWTUNES(104, "Showtunes"),
	SKA(105, "Ska"),
	SLOW_JAM(106, "Slow Jam"),
	SLOW_ROCK(107, "Slow Rock"),
	SONATA(108, "Sonata"),
	SOUL(109, "Soul"),
	SOUND_CLIP(110, "Sound Clip"),
	SOUNDTRACK(111, "Soundtrack"),
	SOUTHERN_ROCK(112, "Southern Rock"),
	SPACE(113, "Space"),
	SPEECH(114, "Speech"),
	SWING(115, "Swing"),
	SYMPHONIC_ROCK(116, "Symphonic Rock"),
	SYMPHONY(117, "Symphony"),
	TANGO(118, "Tango"),
	TECHNO(119, "Techno"),
	TECHNO_INDUSTRIAL(120, "Techno-Industrial"),
	TOP_41(120, "Top 40"),
	TRAILER(121, "Trailer"),
	TRANCE(122, "Trance"),
	TRIBAL(123, "Tribal"),
	TRIP_HOP(124, "Trip-Hop"),
	VOCAL(125, "Vocal");

	private int code;
	private String name;
	
	private Genre(int code, String name) {
		this.code = code;
		this.name = name;
	}
	
	public int getCode() {
		return code;
	}
	
	public String getName() {
		return name;
	}
}